import type { StepRecord } from "../types.js";

const escapeHtml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const renderAudit = (item: StepRecord): string => {
  if (!item.status) {
    return "";
  }
  const parts = [`状态: ${escapeHtml(item.status)}`];
  if (item.errorCode) {
    parts.push(`错误: ${escapeHtml(item.errorCode)}`);
  }
  if (typeof item.retryCount === "number") {
    parts.push(`重试: ${item.retryCount}`);
  }
  if (typeof item.latencyMs === "number") {
    parts.push(`耗时: ${item.latencyMs}ms`);
  }
  return `<p class="step-audit">${parts.join(" | ")}</p>`;
};

const renderUrl = (item: StepRecord): string => {
  if (!item.pageUrlBefore && !item.pageUrlAfter) {
    return "";
  }
  const parts: string[] = [];
  if (item.pageUrlBefore) {
    parts.push(`前URL: ${escapeHtml(item.pageUrlBefore)}`);
  }
  if (item.pageUrlAfter) {
    parts.push(`后URL: ${escapeHtml(item.pageUrlAfter)}`);
  }
  return `<p class="step-url">${parts.join(" | ")}</p>`;
};

export const buildManualHtml = (runId: string, generatedAt: string, steps: StepRecord[]): string => {
  const body = steps
    .map((item) => {
      const action = item.action ? `<p class="step-action">动作: ${escapeHtml(item.action)}</p>` : "";
      const image = item.image
        ? `<div class="screenshot"><img class="step-image" src="${escapeHtml(item.image)}" alt="步骤 ${item.step} 截图"></div>`
        : "";
      return `
        <div class="step">
            <h2 class="step-title">步骤 ${item.step}</h2>
            ${action}
            <p class="step-desc">${escapeHtml(item.desc)}</p>
            ${renderAudit(item)}
            ${renderUrl(item)}
            ${image}
        </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web 操作手册 (Run: ${escapeHtml(runId)})</title>
    <style>
        body { font-family: "Microsoft YaHei", "Segoe UI", sans-serif; margin: 0; padding: 20px; background-color: #f5f7fa; color: #303133; }
        .container { max-width: 1000px; margin: 0 auto; background-color: #ffffff; padding: 36px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.08); }
        h1 { text-align: center; color: #409eff; border-bottom: 2px solid #ebeef5; padding-bottom: 16px; margin: 0 0 16px; }
        .meta { text-align: center; color: #909399; margin-bottom: 26px; font-size: 14px; }
        .meta .run-id { display: inline-block; margin-left: 8px; padding: 2px 8px; border-radius: 999px; background: #ecf5ff; color: #409eff; }
        .step { margin-bottom: 24px; padding: 20px; border: 1px solid #ebeef5; border-radius: 6px; background-color: #fafafa; }
        .step-title { margin: 0 0 10px; color: #303133; font-size: 20px; }
        .step-action { margin: 0 0 10px; color: #909399; font-size: 13px; letter-spacing: 0.3px; }
        .step-desc { margin: 0; color: #606266; font-size: 16px; line-height: 1.7; }
        .step-audit { margin: 10px 0 0; color: #606266; font-size: 13px; line-height: 1.6; }
        .step-url { margin: 6px 0 0; color: #909399; font-size: 12px; line-height: 1.5; word-break: break-all; }
        .screenshot { margin-top: 18px; text-align: center; }
        .step-image { max-width: 100%; border: 1px solid #dcdfe6; border-radius: 6px; box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1); }
        .footer { text-align: center; color: #909399; margin-top: 32px; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Web 自动化操作手册</h1>
        <p class="meta">生成时间: ${escapeHtml(generatedAt)}<span class="run-id">Run: ${escapeHtml(runId)}</span></p>
${body}
        <div class="footer">
            <p>Generated by TRAE Web Manual Agent</p>
        </div>
    </div>
</body>
</html>`;
};
